tap "1password/tap"
tap "domt4/autoupdate"
tap "hashicorp/tap"
tap "ngrok/ngrok"
tap "oven-sh/bun"
brew "autoconf"
brew "automake"
brew "awscli"
brew "carapace"
brew "node"
brew "cloudflare-wrangler"
brew "libtool"
brew "libpq"
brew "php"
brew "composer"
brew "coreutils"
brew "deno"
brew "difftastic"
brew "ffmpeg"
brew "fzf"
brew "gemini-cli"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "libksba"
brew "gnupg"
brew "graphviz"
brew "htop"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "lefthook"
brew "libyaml"
brew "mas"
brew "mole"
brew "neovim"
brew "nvm"
brew "pinentry-mac"
brew "pkgconf"
brew "pnpm"
brew "pv"
brew "rbenv"
brew "redis"
brew "ripgrep"
brew "shfmt"
brew "sox"
brew "stow"
brew "stripe-cli"
brew "tmux"
brew "trash", link: true
brew "whisper-cpp"
brew "yarn"
brew "zlib"
brew "zoxide"
brew "hashicorp/tap/terraform"
brew "oven-sh/bun/bun"
cask "1password", args: { appdir: "/Applications" }
cask "1password-cli"
cask "arc"
cask "battery"
cask "chatgpt"
cask "chatgpt-atlas"
cask "claude"
cask "cursor"
cask "docker-desktop", args: { appdir: "/Applications" }
cask "drawpen"
cask "figma"
cask "firefox", args: { appdir: "/Applications" }
cask "ghostty"
cask "gimp"
cask "google-chrome", args: { appdir: "/Applications" }
cask "iterm2"
cask "keycastr"
cask "kitty"
cask "linear-linear"
cask "loom"
cask "microsoft-excel"
cask "microsoft-word"
cask "ngrok"
cask "notion", args: { appdir: "/Applications" }
cask "notion-calendar"
cask "notion-mail"
cask "obs"
cask "openvpn-connect"
cask "orbstack"
cask "postman", args: { appdir: "/Applications" }
cask "raycast"
cask "slack"
cask "sublime-text"
cask "tableplus"
cask "telegram", args: { appdir: "/Applications" }
cask "visual-studio-code", args: { appdir: "/Applications" }
cask "vlc"
cask "windsurf"
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "TestFlight", id: 899247664
mas "WhatsApp", id: 310633997
mas "Xcode", id: 497799835
