# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

os:
  editPreset: "nvim"
git:
  overrideGpg: true
  diffContextSize: 20
  pagers:
    - name: side-by-side
      colorArg: always
      pager: delta --side-by-side --paging=never --line-numbers-left-format="" --line-numbers-right-format="" --wrap-max-lines=unlimited --line-fill-method=spaces
    - name: unified
      colorArg: always
      pager: delta --paging=never --line-numbers-left-format="" --line-numbers-right-format="" --wrap-max-lines=unlimited --line-fill-method=spaces
gui:
  sidePanelWidth: 0.30
  expandFocusedSidePanel: true
  theme:
    activeBorderColor:
      - bold
  showNumstatInFilesView: true
  showBottomLine: false
  nerdFontsVersion: "3"
  scrollHeight: 1
