#!/bin/bash
set -euo pipefail

# Codex reads global instructions from ~/.codex/AGENTS.md and has no include
# syntax, so the canonical files in dotfiles/agents/.agents/instructions/ are
# concatenated into a single generated file.

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTRUCTIONS_DIR="$REPO_DIR/dotfiles/agents/.agents/instructions"
OUT_FILE="$REPO_DIR/dotfiles/codex/.codex/AGENTS.md"

mkdir -p "$(dirname "$OUT_FILE")"

{
  echo "<!-- Generated by scripts/build-codex-agents-md.sh - do not edit. -->"
  echo "<!-- Edit dotfiles/agents/.agents/instructions/ and re-run the script. -->"
  for f in identity responding build-mode coding-preferences tooling-preferences; do
    echo
    cat "$INSTRUCTIONS_DIR/$f.md"
  done
} >"$OUT_FILE"

echo "Wrote $OUT_FILE"
